# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAe9P9rK_WwkaJ3-6JiGUjHN9rBfkHSS
"""



import cv2
import numpy as np
from pathlib import Path
from typing import Union

class ImageProcessor:
    """
    Object-oriented wrapper for standard OpenCV image transformations.
    Replaces procedural notebook code with reusable methods and state management.
    """
    def __init__(self, image_path: Union[str, Path]):
        self.image_path = Path(image_path)
        self.image = None
        self.processed_image = None
        self._load_image()

    def _load_image(self) -> None:
        """Internal helper to load the image from disk safely."""
        if not self.image_path.exists():
            raise FileNotFoundError(f"Image not found at: {self.image_path}")

        self.image = cv2.imread(str(self.image_path))
        if self.image is None:
            raise ValueError(f"Failed to decode image at: {self.image_path}")

        # Default processed image starts as a copy of the original
        self.processed_image = self.image.copy()

    def convert_to_grayscale(self) -> 'ImageProcessor':
        """Converts the current image to grayscale."""
        if len(self.processed_image.shape) == 3:
            self.processed_image = cv2.cvtColor(self.processed_image, cv2.COLOR_BGR2GRAY)
        return self

    def apply_gaussian_blur(self, kernel_size: tuple = (5, 5)) -> 'ImageProcessor':
        """Applies a Gaussian blur filter to reduce noise."""
        self.processed_image = cv2.GaussianBlur(self.processed_image, kernel_size, 0)
        return self

    def apply_canny_edges(self, threshold1: int = 100, threshold2: int = 200) -> 'ImageProcessor':
        """Applies Canny edge detection."""
        # Ensure image is grayscale first for Canny
        if len(self.processed_image.shape) == 3:
            gray = cv2.cvtColor(self.processed_image, cv2.COLOR_BGR2GRAY)
        else:
            gray = self.processed_image

        self.processed_image = cv2.Canny(gray, threshold1, threshold2)
        return self

    def save_output(self, output_path: Union[str, Path]) -> None:
        """Saves the currently processed image to disk."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        success = cv2.imwrite(str(output_path), self.processed_image)
        if not success:
            raise IOError(f"Failed to save processed image to: {output_path}")

