# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAe9P9rK_WwkaJ3-6JiGUjHN9rBfkHSS
"""



from numpy._core import numeric
# exploratory data analysis
import pandas as pd
import numpy as np
from typing import Dict

class EDAreporter :
  # encopsulates data set summery statistics and uotlier detection
  def __init__(self, df:pd.DataFrame):
    self.df = df


  def get_summary_status(self)->Dict[str, dict]:
    return self.df.describe().to_dict()

  def detect_missing_values(self)-> pd.Series:
    return self.df.isnull().sum()
  def  calculate_correlation_matrix(self)->pd.DataFrame:
    numeric_df = self.df.select_dtypes(include=[np.number])
    return numeric_df.corr()

