# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAe9P9rK_WwkaJ3-6JiGUjHN9rBfkHSS
"""



import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



class dataset_load :
# "handles loading and intial spliting of the dataset"
     def __init__(self, filepath = str):
         self.filepath = filepath


     def load_data(self)-> pd.DataFrame:
         df = pd.read_csv(self.filepath)
         return df

class data_prepocessors:
  # preprocessing of the data can be done like cleaning imputation and feature engg
      def __init__(self):
        self.imputer = SimpleImputer(strategy= "mean")
        self.scaler = StandardScaler()

      def transform(self, df: pd.DataFrame)-> pd.DataFrame:
          if "Credit_Score" in df.columns :
            df['Credit_Score_sq']  =  df['Credit_Score']**2
          if "DIT_Ratio" in df.columns :
            df["DIT_Ratio_sq"] = df['DIT_Ratio']**2
          return df

class LoanModelPipeline:
  # traing and evaluation using the oops
  def __init__(self,model =None):
    self.model = model if model else LogisticRegression()
  def train(self,X_train:np.ndarray, y_train :np.ndarray):
    self.model.fit(X_train, y_train)
  def evaluate(self, X_test: np.ndarray,y_test: np.ndarray):
    prediction =  self.model.predict(X_test)
    acc = accuracy_score(y_test, prediction)
    report =  classification_report(y_test, prediction, output_dict = True)
    conf_matrics = confusion_matrix(y_test, prediction)
    return {acc,
            report,
            conf_matrics
    }

