# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAe9P9rK_WwkaJ3-6JiGUjHN9rBfkHSS
"""



# web scraping or data upillity
import requests
from bs4 import BeautifulSoup
from typing import List, Dict
import pandas as pd



class SimpleWebScrapper:
  # object oriented web scrapper for extracting structural data cleanly
  def __init__ (self, base_url : str ):
    self.base_url =base_url
    self.soup = None

  def fetch_page(self)-> None :
    response = requests.get(self.base_url)
    response.raise_for_status()
    self.soup = BeautifulSoup(response.text, "html.parser")


  extract_heading = lambda self, tag="h2":[h.get_text(strip = True) for h in self.soup.find_all(tag)] if self.soup else[]

